version: '3.3'
services:
    conga-jupyter:
        image: conga-jupyter
        container_name: conga-jupyter
        build: .
        ports:
            - '8888:8888'
        volumes:
            - '${PWD}/data:/home/jovyan/conga/data'
            - '${PWD}/scripts:/home/jovyan/conga/my_scripts'
